### ISSUE TITLE
Is the code somewhere else?

### ISSUE THREAD

**Issue by Codename-01** [tsaishien-chen/IFND#2]
I found this repo from your paper "INCREMENTAL FALSE NEGATIVE DETECTION FOR CONTRASTIVE LEARNING", but this repo seems to be empty.
Is this code available somewhere, or haven't been published yet?

**Comment by tsaishien-chen** [comment]
I am doing military service and cannot organize the code recently. The code might be released early next year.
Sorry for your inconvenience.
